name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_run:
    workflows: ["Update Calendso"]
    branches: [main]
    types: [completed]
  workflow_dispatch:

env:
  SKIP_DB_DEPLOY: "true" # Skip migrations during build
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: calendso
  DATABASE_HOST: postgres

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git submodule update
        run: git submodule update --init

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: officialmoadel/cal
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            SKIP_DB_DEPLOY=${{ env.SKIP_DB_DEPLOY }}
            NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
            NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
            DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@${{ env.DATABASE_HOST }}/${{ env.POSTGRES_DB }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
